Testing.Web/Controllers/AdminController.cs
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using Testing.Domain.Entitys;
using Testing.Domain.Interface;

namespace Testing.Web.Controllers
{
    [Authorize(Roles="admin")]
    public class AdminController : Controller
    {
        private IRepositoryAdmin repository;
        public AdminController(IRepositoryAdmin r)
        {
            repository = r;
        }

        // GET: Admin
        public ActionResult Index()
        {
            ViewBag.CountUsers = repository.CountUsers();
            ViewBag.CountTests = repository.CountTests();
            return View();
        }

        // Get: получение всех юзеров
        public ActionResult Users()
        {
            var c = repository.GetUsers();
            return View(c);
        }

        // блокировка и разблокировка юзера
        public ActionResult BlockUnBlock(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            repository.BlockUser(id);
            return View("Users", repository.GetUsers());
        }

        // удаление юзера
        public ActionResult Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            repository.DeleteUser(id);
            return View("Users", repository.GetUsers());
        }

        // получения списка тестов
        public ActionResult Tests()
        {
            return View(repository.GetTests());
        }

        // soft удаления теста
        public ActionResult DeleteTest(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            repository.DeleteTest(id);
            return View("Tests", repository.GetTests());
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.СomplexityId = new SelectList(repository.GetСomplexity(), "Id", "Complication");
            return View();
        }

        // POST: Tests/Create
        [HttpPost] 
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Subject,TimeToGo,CountQuestions,СomplexityId")] Test test)
        {
            if (ModelState.IsValid)
            {
                repository.AddTest(test);
                return RedirectToAction("AddInformation/" + test.Id);
            }
            ViewBag.СomplexityId = new SelectList(repository.GetСomplexity(), "Id", "Complication", test.СomplexityId);
            return View(test);
        }

        public ActionResult AddInformation(int? id)
        {
            return View(repository.GetTest(id));
        }

        // добавления вопросв по тесту
        [HttpPost]
        public string AddQuestion(string name, string idtest, List<string> answers, List<string> ans)
        {
            var result = repository.AddQuestion(name, idtest, answers, ans);
            return result.ToString();
        }

        // отображения view с изменение информации о тесте
        [HttpGet]
        public ActionResult EditTestInfo(int? id)
        {
            if(id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var t = repository.GetTest(id);
            if(t == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            ViewBag.СomplexityId = new SelectList(
                repository.GetСomplexity(),
                "Id", 
                "Complication",
                selectedValue: t.СomplexityId);

            return View(t);
        }

        // сохранение информации о тесте
        [HttpPost]
        public ActionResult EditTestInfo(Test test)
        {
            repository.EditTestInformation(test);
            return RedirectToAction("Tests");
        }
    }
}

Testing.Web/Controllers/UserController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Testing.Domain.Interface;

namespace Testing.Web.Controllers
{
    [Authorize(Roles = "user")]
    public class UserController : Controller
    {
        private IRepositoryUser repository;
        public UserController(IRepositoryUser r)
        {
            repository = r;
        }

        public ActionResult Index()
        {
            ViewBag.CountTests = repository.CountTests(User.Identity.Name);
            return View();
        }

        // получения списка тестов
        public ActionResult Tests()
        {
            if(repository.IsBlockUser(User.Identity.Name))
                return View("BlockUser");

            return View(repository.FirstOpenPage(User.Identity.Name));
        }

        public ActionResult Start(int? id)
        {
            var b = repository.Test(id, User.Identity.Name);
            if (b)
            {
                return RedirectToAction("Tests");
            }

            var result = repository.StartTest(id, User.Identity.Name);
            ViewBag.Time = result.time;
            // название теста
            ViewBag.Subject = result.subject;
            // количество вопросов
            ViewBag.CountQuestion = result.countQuestions;
            // номер вопроса
            ViewBag.Num = 1;

            return View(result.question);
        }

        [HttpPost]
        public ActionResult AddUserAnswer(int idtest, int idquest, int num, List<int> idans)
        {
            repository.SaveUserAnswer(idtest, idquest, idans, User.Identity.Name);
            
            var test = repository.CountQuestions(idtest); //context.Tests.Find(idtest);

            if (num == test)
            {
                ViewBag.YourAns = repository.Result(idtest, User.Identity.Name);
                return PartialView("_Result");
            }

            int numc = num + 1;
            ViewBag.Num = numc;
            ViewBag.CountQuestion = test;
           
            var result = repository.NextQuestion(idtest, numc);

            return PartialView("_QuestionPartial", result);
        }

        // результаты по тестам
        public ActionResult Results()
        {
            var result = repository.AllResults(User.Identity.Name);

            return View(result);
        }

        public ActionResult Contact()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Submit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Submit(string subject, string level)
        {
            return View("Tests", repository.GetTestForUser(User.Identity.Name, subject, level));
        }
    }
}

Testing.Web/Views/Shared/AddQuestion.cshtml
@model IEnumerable<Testing.Domain.Entitys.Test>

<div id="searchresults">
        <ul>
        @foreach (var item in Model)
        { 
            <li>@item.Subject</li>
        }
    </ul>
</div>

Testing.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (User.IsInRole("admin"))
                {
                    @Html.ActionLink("Тестирование", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
                }
                else if (User.IsInRole("user"))
                {
                    @Html.ActionLink("Тестирование", "Index", "User", new { area = "" }, new { @class = "navbar-brand" })
                }
                else
                {
                    @Html.ActionLink("Тестирование", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("admin"))
                    {
                        @Html.Partial("_MenuAdmin")
                    }
                    @if (User.IsInRole("user"))
                    {
                        @Html.Partial("_MenuUser")
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <footer>
        <p>&copy; @DateTime.Now.Year – Sheviak Kyrylo</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Testing.Web/Views/Shared/_MenuAdmin.cshtml
<li>@Html.ActionLink("Тесты", "Tests", "Admin")</li>
<li>@Html.ActionLink("Пользователи", "Users", "Admin")</li>

Testing.Web/Views/Shared/_MenuUser.cshtml
<li>@Html.ActionLink("Тесты", "Tests", "User")</li>
<li>@Html.ActionLink("Результаты", "Results", "User")</li>
<li>@Html.ActionLink("Контакты", "Contact", "User")</li>

Testing.Web/Views/Shared/_QuestionPartial.cshtml
@model Testing.Domain.Entitys.Question

<div id="questions">
    <h4>Вопрос:&nbsp;</h4>
    <h4>@ViewBag.Num</h4>
    <h4>&nbsp;/&nbsp;</h4>
    <h4 name="countQuestion">@ViewBag.CountQuestion</h4>
</div>

<input type="hidden" name="idtest" value="@Model.TestId" />
<input type="hidden" name="idquest" value="@Model.Id" />
<input type="hidden" name="num" value="@ViewBag.Num" />

<h3>@Model.UserQuestion</h3>
@foreach (var item in Model.Answers)
{
    <div>
        <input type="checkbox" value="@item.Id" name="idans">
        <label>@item.UserAnswer</label>
    </div>
}
 <br />
<input type="submit" class="btn btn-success" />

Testing.Web/Views/Shared/_Result.cshtml
<h4>Вы ответили правильно на @ViewBag.YourAns %</h4>

@Html.ActionLink("К тестам", "Tests")
@Html.ActionLink("К результатам", "Results")